module.exports.toBeRemovedCategories = [
  // Original List (kept for completeness, duplicates like "contact us" can be removed if needed)
  "home",
  "about us",
  "contact us",
  "skip to main content",
  "blog",
  "facebook",
  "twitter",
  "instagram",
  "linkedin",
  "click to search",
  "click to browse",
  "privacy policy",
  "terms of service",
  "return policy",
  "shipping policy",
  "services",
  "request",
  "quote",
  "careers",
  "faq",
  "faqs",
  "help",
  "support",
  "sitemap",
  "search",
  "skip to content",
  "videos",
  "images",
  "documents",
  "files",
  "downloads",
  "title",
  "login",
  "signin",
  "signup",
  "register",

  // --- New Additions: Extended E-commerce & UI Text ---
  // **Account & User Actions**
  "my account",
  "account",
  "logout",
  "forgot password",
  "reset password",
  "wishlist",
  "my wishlist",
  "save for later",

  // **Cart & Checkout Process**
  "your cart",
  "shopping cart",
  "cart",
  "checkout",
  "proceed to checkout",
  "view cart",
  "update cart",
  "continue shopping",
  "order summary",
  "billing address",
  "shipping address",
  "payment method",
  "place order",
  "order confirmation",

  // **E-commerce Actions**
  "add to cart",
  "add to bag",
  "buy now",
  "select options",
  "view details",
  "learn more",
  "read more",
  "shop now",
  "view all",
  "view more",
  "view product",
  "view collection",

  // **E-commerce Sections**
  "shop all",
  "collections",
  "products",
  "new arrivals",
  "bestsellers",
  "best sellers",
  "sale",
  "clearance",
  "deals",
  "specials",
  "discounts",
  "promotions",
  "gift cards",
  "wish list",
  "recently viewed",

  // **Legal & Policies (Extended)**
  "cookies policy",
  "cookie policy",
  "cookies",
  "refund policy",
  "terms and conditions",
  "legal",
  "disclaimer",

  // **Company Info (Extended)**
  "our story",
  "testimonials",
  "reviews",
  "press",
  "news",
  "events",
  "investors",
  "affiliates",
  "partners",

  // **Utility & Navigation**
  "filter",
  "sort by",
  "apply filters",
  "clear all",
  "menu",
  "close",
  "submit",
  "apply",
  "subscribe",
  "newsletter",
  "email address",
  "not found",
  "404",
  "loading",
  "success",
  "error",
];
